name: Executar testes com pytest
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout my own code
              uses: actions/checkout@v3

            - name: Configure python version
              uses: actions/setup-python@v3
              with:
                python-version: 3.9

            - name: Install requirements
              run: |
                  pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Rodar os testes com pytest
              run: pytest -v